### ISSUE TITLE
Backend Implementation for Create and Read Blog Posts

### ISSUE THREAD

**Issue by varma-101** [jinx-vi-0/BlogLog#1]
Description: The current application lacks the backend functionality to create and read blog posts. I would like to implement two key features:
Create a Blog Post: Implement an API endpoint that allows users to submit and store blog posts in the MongoDB database.
Read Blog Posts: Implement an API endpoint that allows users to retrieve individual blog posts or a list of all posts from the database.

**Comment by adarsh-site** [comment]
Assigned @varma-101 

Please make all the required changes and submit a detailed PR.

**Comment by varma-101** [comment]
Please add level also for project.

**Comment by ar1701** [comment]
I want to contribute on this, can you please assign it to me ?

**Comment by adarsh-site** [comment]
> Please add level also for project.

I'll add Level after reviewing your PR

**Comment by shreyamaheshwari1** [comment]
@jinx-vi-0 can this be assigned to me too ? I can also implement it as it is still open.

**Comment by varma-101** [comment]
@jinx-vi-0 please review my pr i've also added the screenshot to it.

**Comment by varma-101** [comment]
please add hacktoberfest label also
