### ISSUE TITLE
DOC: Add Code of Conduct File for BlogLog Website

### ISSUE THREAD

**Issue by HarshadaGirase** [jinx-vi-0/BlogLog#10]
Description:

BlogLog currently lacks a "Code of Conduct" file in the repository. A Code of Conduct helps to maintain a respectful and inclusive community for all contributors. This issue is to create and add a CODE_OF_CONDUCT.md file to the root directory of the BlogLog website repository.

Purpose:
To ensure a safe, welcoming, and professional environment for all contributors and users of BlogLog.

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by RishiVT2004** [comment]
I will be intrested to work in it

**Comment by adarsh-site** [comment]
Assigned @HarshadaGirase

**Comment by adarsh-site** [comment]
refer issue #24 

submit a single pr with a complete documentation update.

**Comment by HarshadaGirase** [comment]
Okay
@jinx-vi-0  kindly assign #24 issue to me ASAP

**Comment by HarshadaGirase** [comment]
With level label
