### ISSUE TITLE
Fix Two Navbar on Main Page

### ISSUE THREAD

**Issue by ParasY1724** [jinx-vi-0/BlogLog#100]
**Describe the bug**
Two Navbar are rendered on Page instead of one.
&
Once You are logged in /dashboard gives error

**To Reproduce**
1. Go to 'http://localhost:5000/'
2. See error

**Screenshots**
![Screenshot From 2024-10-29 13-37-44](https://github.com/user-attachments/assets/9491e726-c2d4-4f95-a786-8ccb29fb7d70)

![Screenshot From 2024-10-29 14-03-02](https://github.com/user-attachments/assets/9d16a357-82a9-4d6e-a073-4a4c7b934aaa)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by shibasarkar** [comment]
@ParasY1724  buddy I already fixed it #99
