### ISSUE TITLE
After Login /dashboard page is not accessible

### ISSUE THREAD

**Issue by ParasY1724** [jinx-vi-0/BlogLog#101]
**Describe the bug**
After Login /dashboard page is not accessible gives error, i current logic main layout is used but we should use admin layout for admin pages.

**To Reproduce**
1.Login
2. go to /dashboard
3. See error

**Screenshots**
![Screenshot From 2024-10-29 14-03-02](https://github.com/user-attachments/assets/e074a7d3-705c-40a6-8b1b-42b71ac8a8f8)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by adarsh-site** [comment]
Find out why it's not working.

**Comment by ParasY1724** [comment]
> Find out why it's not working.

Yes i did it is applying layout of main i.e main header is begin applied for admin routes which don't have currentRoute so instead for admin routes we should apply admin layout

**Comment by adarsh-site** [comment]
Assigned @ParasY1724

**Comment by adarsh-site** [comment]
good work
