### ISSUE TITLE
Improve the unauthorize response 

### ISSUE THREAD

**Issue by shibasarkar** [jinx-vi-0/BlogLog#102]
**Describe the bug**
When I try to add a post without login it shows me a JSON response on the page 

**To Reproduce**
1. Go to any post button 
2. Click on 
3. See error

**Screenshots**
![Screenshot 2024-10-29 142825](https://github.com/user-attachments/assets/33f9cad4-d5a2-4169-bafb-e2224e314d74)

**Comment by shibasarkar** [comment]
@jinx-vi-0 can you please assign it to me

**Comment by adarsh-site** [comment]
please explain the issue and your proposed solution.

**Comment by shibasarkar** [comment]
When a user try to add a post without login 
We need show some appropriate response page 
Right now it's show's a json response with a message unauthorized

**Comment by shibasarkar** [comment]
I want to a add response page when  user add a post 
Without login 
Either it's redirect to the login page or it's show's something that says you need to login for making a post
