### ISSUE TITLE
Enhance "Create Post" Page for Expanded Typing Area

### ISSUE THREAD

**Issue by rishabh7923** [jinx-vi-0/BlogLog#105]
### 🙋‍♂️ Problem
Yes, As of now when you create post, you have very limited space to type.
![image](https://github.com/user-attachments/assets/277a66f2-88dd-4cbe-9ecc-6c84a12d7f19)

### ✅ Solution
 i would like to make this similar to edit page which would allow us to add more option such as markdown and stuff in future.

![image](https://github.com/user-attachments/assets/2cc0d4d7-e2d9-40b8-ab31-20a10b970dbd)

**Comment by adarsh-site** [comment]
Assigned @rishabh7923
