### ISSUE TITLE
Allow users to optionally set an image for their blog post.

### ISSUE THREAD

**Issue by rishabh7923** [jinx-vi-0/BlogLog#106]
When creating a post, users and admins can choose any image for the blog, which I believe adds a nice touch to the overall presentation.

I am thinking of using Cloudinary for image hosting

**Comment by adarsh-site** [comment]
Assigned @rishabh7923

**Comment by rishabh7923** [comment]
@jinx-vi-0 you forgot to assign me 😓

**Comment by rishabh7923** [comment]
I think this was definitely level 3

**Comment by rishabh7923** [comment]
Please do the same on Pull request 🤧
