### ISSUE TITLE
Implement Markdown in blog description

### ISSUE THREAD

**Issue by rishabh7923** [jinx-vi-0/BlogLog#107]
**Is your feature request related to a problem? Please describe.**
Yes, currently the blog feels quite shabby and lacks proper headings and other components.

**Describe the solution you'd like**
I would like to implement markdown in the blog description, allowing users to utilize markdown tags for formatting options like bold, italic, and headings.

**Comment by adarsh-site** [comment]
Assigned @rishabh7923
