### ISSUE TITLE
Adding Server Side Validation for Create Post & Contact Us Route

### ISSUE THREAD

**Issue by ParasY1724** [jinx-vi-0/BlogLog#109]
**Is your feature request related to a problem? Please describe.**
Adding Validation for create post ensures that no post request is forward with empty fields.
Adding Validation for Contact Us Ensures that only valid email address is begin used.

**Current Problems:**
**1. Invalid Email :**

https://github.com/user-attachments/assets/d3c7a0d9-57ea-4710-a8f6-90353b1e8b70

**2. Post with empty field**

https://github.com/user-attachments/assets/84de8049-816a-43c0-9ab4-e53092798e65

**Comment by adarsh-site** [comment]
Assigned @ParasY1724
