### ISSUE TITLE
Input Validation for admin register

### ISSUE THREAD

**Issue by MKisKrazy** [jinx-vi-0/BlogLog#11]
There is no proper input validation set up already for Admin Register.  
i would like to add input validation to avoid dummy registers especially for admin.
can you please assign me this? @jinx-vi-0

**Comment by adarsh-site** [comment]
Assigned @MKisKrazy

**Comment by MKisKrazy** [comment]
@jinx-vi-0  when i start server , it says MongooseServerSelectionError and the server disconnects. i set the url properly though.

**Comment by rishabh7923** [comment]
I can see that this issue has been resolved as I was hoping, but in the current version of this project, there is no input validation. If it's okay with everyone, I would like to work on implementing input validation on both the client and server sides.

**Comment by adarsh-site** [comment]
@rishabh7923 open a new issue regarding this. I' ll assign it to you.

**Comment by rishabh7923** [comment]
@jinx-vi-0 #80
