### ISSUE TITLE
Add JWT_SECRET to .env file instructions in README

### ISSUE THREAD

**Issue by deepakcs2003** [jinx-vi-0/BlogLog#110]
Contributors face issues setting up the repo because the README only mentions MONGODB_URI for the .env file, but JWT_SECRET is also needed to run the app.

![image](https://github.com/user-attachments/assets/68fa218b-3c4a-4af3-bfdc-54d2f2221d34)

Solution: Update the README to include JWT_SECRET in the .env instructions

MONGODB_URI=mongodb://localhost:27017/bloglog
JWT_SECRET=your-secret-key

Additional Context: This will help avoid setup errors and improve the onboarding process for contributors.

**Comment by deepakcs2003** [comment]
Please assign this issue to me, as I'd like to contribute by adding JWT_SECRET to the .env setup in the README. Thanks

**Comment by adarsh-site** [comment]
we are no longer distributing points for doc updates,  still If u want to update it, you are good to go.
