### ISSUE TITLE
Feat:adding a new page to display all contributors✨

### ISSUE THREAD

**Issue by yashksaini-coder** [jinx-vi-0/BlogLog#116]
**Is your feature request related to a problem? Please describe.**
I would like to add the contributors page to show the efforts of others & mine included

**Describe the solution you'd like**
To add a contributors page to display all the contributors

@jinx-vi-0 can you assign me this issue

**Comment by adarsh-site** [comment]
There is no need to add contributor page on the website. It is already present on gitHub repo.
