### ISSUE TITLE
Feature : Adding Social Media Sharing for Blog Posts

### ISSUE THREAD

**Issue by sumitkumar9128** [jinx-vi-0/BlogLog#13]
**Description**:
Implement social media sharing buttons on each blog post. Users should be able to share their blog posts directly to popular platforms such as Facebook, Twitter, LinkedIn, etc. Each post will have its own sharing buttons, allowing users to easily distribute their content.

**Implementation Details**:
- Add share buttons for Facebook, Twitter, LinkedIn on the blog post page.
- Use platform specific APIs or URL schemes to share content.
- The buttons should automatically include the blog post title and a link to the post.

**Benefits**:
- Increases user engagement and encourages content sharing.
- Drives more traffic to the platform.
- Enhances user experience with easy social sharing.

**Comment by sumitkumar9128** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by sumitkumar9128** [comment]
please assign with label **gssoc-ext**, **hacktoberfest-acceted** and also set **level-2** or **level-3**

**Comment by sumitkumar9128** [comment]
please assign

**Comment by adarsh-site** [comment]
Assigned @sumitkumar9128

**Comment by sumitkumar9128** [comment]
thank you
