### ISSUE TITLE
Development of Responsive "About Us" Page

### ISSUE THREAD

**Issue by smrutiranjanbhuyan** [jinx-vi-0/BlogLog#18]
Create a responsive About Us page that showcases our organization's mission, team, and contact information. Ensure the page is visually appealing .

**Comment by smrutiranjanbhuyan** [comment]
@jinx-vi-0 I’d like to work on the responsive 'About Us' page. Please assign it to me. Thank you!

**Comment by pranavi2** [comment]
@jinx-vi-0 I'd love to work on the 'About Us' page. I'll make it fully responsive using flexbox or CSS grid and ensure it looks sleek on all devices. The focus will be on clean design, smooth animations, and accessibility. Please assign it to me!

**Comment by adarsh-site** [comment]
Assigned @smrutiranjanbhuyan
