### ISSUE TITLE
[FEATURE] Adding the Option for Uploading Profile Image for The User

### ISSUE THREAD

**Issue by MOHINI1403** [jinx-vi-0/BlogLog#19]
I would like to contribute in creating the backend such that users can also upload their profile images or coverImages and they are taken from the user via multer and stored in cloudinary . I would like to contribute in contributing to this.
Since i was assigned the issue to work on models I would love to add this portion also .
Please assign me this issue so that I could work on this. 
Thank You

**Comment by ParasharDeb** [comment]
i was wondering if you can assign me this issue

**Comment by adarsh-site** [comment]
Assigned @MOHINI1403

**Comment by MOHINI1403** [comment]
Okie will work on the entire backend and would raise the PR by today . 
Thank you for assigning the issue.
