### ISSUE TITLE
Implement Blog Creation and Retrieval API Endpoints

### ISSUE THREAD

**Issue by ShaikHafiza** [jinx-vi-0/BlogLog#2]
Overview: The current application is missing the necessary backend infrastructure to handle the creation and retrieval of blog posts. This issue focuses on building the backend functionality using Express.js to support the following operations:

Create a new blog post: Accept user input (blog title, content, author) and store it in a database.
Retrieve blog posts: Provide the ability to fetch individual posts by ID or a list of all posts.
Goals:

Implement an API endpoint (POST /api/blogs) that allows users to submit a new blog post.
Implement API endpoints (GET /api/blogs and GET /api/blogs/:id) to fetch either a list of all posts or a specific post based on its ID.
Technical Considerations:

Use Mongoose to define the blog post schema and interact with MongoDB for data persistence.
Implement input validation to ensure valid data is being submitted when creating a post.
Set up proper error handling for cases like missing posts or invalid input data.

**Comment by adarsh-site** [comment]
Assigned @ShaikHafiza .

Please make all the required changes and submit a detailed PR.

**Comment by shreyamaheshwari1** [comment]
@jinx-vi-0 can this be assigned to me too ? I can also implement it as it is still open.
