### ISSUE TITLE
Enhancing Readme.md file

### ISSUE THREAD

**Issue by neeru24** [jinx-vi-0/BlogLog#23]
Hey..

I want to suggest that we can make readme file even more ATTRACTIVE and make it visually appealing..

Kindly assign me this, I want to contribute.

**Comment by adarsh-site** [comment]
refer issue #24 

submit a single pr with a complete documentation update.

**Comment by neeru24** [comment]
> refer issue #24 
> 
> submit a single pr with a complete documentation update.

Ok
