### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by adarsh-site** [jinx-vi-0/BlogLog#24]
Add or update all the necessary documentation related issue.

update readme
add contribution file
add code of conduct
etc.

**Comment by Shariq2003** [comment]
please assign label of level for gssoc ext and assign this to me.

**Comment by adarsh-site** [comment]
This is an open issue, anyone can take it. Just make sure to send me a ss of the readme before submitting a pr.

**Comment by Shariq2003** [comment]
> This is an open issue, anyone can take it. Just make sure to send me a ss of the readme before submitting a pr.

Okay, working on this

**Comment by Ankesh-erek** [comment]
@jinx-vi-0 sir, Could I please be assigned to this issue?

**Comment by adarsh-site** [comment]
This is an open issue, anyone can take it. Just make sure to send me a ss of the readme before submitting a pr.

**Comment by ananyag309** [comment]
Hi, @jinx-vi-0 
I am unable to start the webapp locally.
I followed the exact steps but its just not working. Is there any chance that readme.md is wrongly updated?
Just help me out with this

**Comment by adarsh-site** [comment]
> Hi, @jinx-vi-0 I am unable to start the webapp locally. I followed the exact steps but its just not working. Is there any chance that readme.md is wrongly updated? Just help me out with this

I guess .env file section in readme is not updated. Follow .env-example file for reference. If you still face any issue, let me know.
