### ISSUE TITLE
Implement Dark mode to the BlogLog application

### ISSUE THREAD

**Issue by AnsharaFayazBeigh** [jinx-vi-0/BlogLog#26]
I would like to propose adding a dark mode feature to the BlogLog application. This feature will enhance user experience, especially for users who prefer reading in low-light environments. Dark mode can also help reduce eye strain and save battery life on devices with OLED screens.

I would really like to work on it! Please assign it to me. 

Also assign relevant labels ( level, gssoc ext and hacktoberfest)

@jinx-vi-0

**Comment by adarsh-site** [comment]
Assigned @AnsharaFayazBeigh

**Comment by AnsharaFayazBeigh** [comment]
@jinx-vi-0  thank you! I am on it!

**Comment by AnshuWorld** [comment]
Please assign me this task under gssoc24 extd

**Comment by AnsharaFayazBeigh** [comment]
@AnshuWorld its already done.
