### ISSUE TITLE
Implement User Signup and Login Functionality

### ISSUE THREAD

**Issue by varma-101** [jinx-vi-0/BlogLog#3]
Overview: This issue focuses on building the user authentication system for the application using Express.js and Passport.js. It will handle signup and login functionalities, allowing users to create accounts and authenticate via local strategy (username and password).

Goals:

Signup functionality: Allow users to register by providing a username, email, and password. Securely store passwords using bcrypt.
Login functionality: Implement login functionality that uses Passport.js for authenticating users with the local strategy (email and password).
Session Management: Use Passport.js to manage user sessions and persistent login across requests.
Technical Considerations:

Use bcrypt to hash and store passwords securely.
Implement Passport.js with the local strategy to handle email/password authentication.
Set up session management with express-session and Passport.js to handle persistent login sessions.
Create the following API routes:
POST /auth/signup: To register a new user.
POST /auth/login: To authenticate users using Passport.js and initiate a session.
GET /auth/logout: To log out a user and destroy their session.
Validate user inputs during signup to ensure strong passwords and valid email addresses.

**Comment by adarsh-site** [comment]
Assigned @varma-101

**Comment by varma-101** [comment]
please add the labels hacktoberfest and gssoc-extd

**Comment by ShaikHafiza** [comment]
I want to work on this

**Comment by ankurrrrr7** [comment]
ASSIGN  me please @jinx-vi-0

**Comment by ekayZ7875** [comment]
Heyy i can help you out with this issue please assign it to me.

**Comment by RiteshS1** [comment]
Hei @jinx-vi-0 ; Is this Issue still open? I dont see any further progress??
I would like to work upon some good backend issues like these! Feel free to assign me one!

**Comment by adarsh-site** [comment]
@varma-101 any update ?

**Comment by varma-101** [comment]
yes i will deliver it tomorrow.Please add level labels to it.

**Comment by varma-101** [comment]
i've created a pr please verify it and add level labels and gssoc and hacktoberfest labels to it.

**Comment by varma-101** [comment]
Bro @jinx-vi-0 please verify it fast.
