### ISSUE TITLE
[Level1 Enhancement] Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [jinx-vi-0/BlogLog#30]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by adarsh-site** [comment]
Assigned @KiranBaliga

**Comment by ghost** [comment]
@jinx-vi-0 Please review and action accordingly. Thank you!
