### ISSUE TITLE
Contact Page and /contact Endpoint Not Working

### ISSUE THREAD

**Issue by rudrapratap63** [jinx-vi-0/BlogLog#37]
I noticed that the contact page and the `/contact` endpoint are not working correctly. When a user clicks on the "`Contact`" button in the navbar, it does not lead to the intended contact page, resulting in either a 404 error or no action at all. 

https://github.com/user-attachments/assets/d51cabef-1b60-41d1-94f2-99c99df8df28

**Steps to Reproduce:**
1. Go to the main page of the project.
2. Click on the "Contact" button in the navigation bar.
3. Observe that no contact page is displayed, or an error is shown.

**Proposed Solution :-**
- Create a Contact Page: Develop a new contact page with a form that allows users to enter their name, email, and message.
- Fix the /contact Endpoint: Ensure that the /contact endpoint correctly routes to the new contact page.
- Update Navbar Link: Verify that the "Contact" button in the navbar correctly points to the /contact endpoint.

**Comment by rudrapratap63** [comment]
@jinx-vi-0 Please assign this issue to me i create contact page with best ui

**Comment by adarsh-site** [comment]
Assigned @rudrapratap63

**Comment by rudrapratap63** [comment]
@jinx-vi-0 Also if you would like to integrate Nodemailer for sending emails, please let me know!

**Comment by adarsh-site** [comment]
@rudrapratap63 
UI is good, but please avoid unnecessary colors. Stick to a black and white color scheme. Also, if possible, integrate Nodemailer.

**Comment by rudrapratap63** [comment]
@jinx-vi-0 
Thank you for your feedback!
I will simplify the color scheme to stick to black and white as you suggested.
Regarding integrating Nodemailer, I will implement that functionality.

**Comment by rudrapratap63** [comment]
@jinx-vi-0, please check the [PR](https://github.com/jinx-vi-0/BlogLog/pull/49). I added the Nodemailer functionality and changed the color scheme to black and white. The video is attached below, so please check that as well. 

https://github.com/user-attachments/assets/d3209a36-e84d-47e2-a7b5-e41915d1770c

**Comment by rudrapratap63** [comment]
@jinx-vi-0  , I hope you’re doing well! I contributed to the issue and noticed it was labeled as Level 1. If possible, could you consider changing it to **Level 3**? I also implemented the `Nodemailer `functionality and created a Contact Us page from scratch, along with a functional backend for it. If you think it fits better, I would appreciate a Level 2 as well. Thank you!

**Comment by adarsh-site** [comment]
@rudrapratap63 good work
