### ISSUE TITLE
Improvising the Data Modelling of the Models and Hashing the Password Before Storage 

### ISSUE THREAD

**Issue by MOHINI1403** [jinx-vi-0/BlogLog#4]
**Current Scenario** : In current scenario the model design of this code is ok but we can improvise this by adding certain functionalities like adding the validation customising the model improvising the code quality and most importantly not storing the password directly into the database as it's not considered as a good practise.
**What Am I Proposing**
I am proposing of utilising the data-modelling library: Mongoose and work on improvising the model schema and also looking into designing the industry standard design hashing the password before storage. 
Please assign me this issue so that I could continue on working on this issue.

**Comment by simmi-verma** [comment]
I would like to contribute in it .Please ssign to me.

**Comment by simmi-verma** [comment]
I would like to contribute in it .

**Comment by adarsh-site** [comment]
Assigned @MOHINI1403

**Comment by MOHINI1403** [comment]
Thank you for assigning the issue i will work on this and raise the PR.
