### ISSUE TITLE
Integrate Google and Facebook-Oauth in signup page

### ISSUE THREAD

**Issue by srivastav2006** [jinx-vi-0/BlogLog#42]
# ✨ Feature Request

### **Feature Description**
Add Google and Facebook OAuth on the signup page to allow users to register and log in using their social accounts.

### **Problem Statement**
The current signup process is limited to email registration, which may discourage users. Social logins will enhance user convenience and boost signup rates.

### **Proposed Solution**
Add "Sign up with Google" and "Sign up with Facebook" buttons on the signup page, enabling single-click registration via OAuth.

### **Alternatives Considered**
- Implementing only one OAuth option.
- Exploring other social platforms like Twitter or Apple, but focusing on Google and Facebook due to larger user bases.

### **Additional Context**
Requires Google and Facebook developer console setup and backend token management for secure integration.

**Comment by nrv28** [comment]
Please assign me this issue

**Comment by adarsh-site** [comment]
Assigned @srivastav2006
