### ISSUE TITLE
 Change MONGODB_URI from mongodb://localhost:27017/bloglog to mongodb://127.0.0.1:27017/bloglog

### ISSUE THREAD

**Issue by Dnyaneshpise** [jinx-vi-0/BlogLog#5]
To avoid potential issues related to `localhost` DNS resolution on certain systems, I propose changing it to:
#### I encountered an issue where MongoDB failed to connect using `localhost`. This resulted in errors and delays during development. Changing `localhost` to `127.0.0.1` resolved the issue immediately. Here's a screenshot of the error I faced:

![image](https://github.com/user-attachments/assets/c4663993-8271-4679-92bf-1c2fbbd3167a)

## Reason for Change
- `localhost` may sometimes resolve incorrectly due to system or network configurations, which can lead to connection issues with MongoDB.
- Using `127.0.0.1` explicitly references the loopback address and is generally more reliable across different environments.

## Steps to Reproduce
1. On certain systems, running the app with the current `MONGODB_URI` may cause MongoDB connection issues.
2. Changing `localhost` to `127.0.0.1` resolves the issue.

## Proposed Solution
Update the `.env` file to use the following:

**Comment by Dnyaneshpise** [comment]
Hey! I would love to resolve this issue quickly so that others can run the project locally and contribute to various features. Please assign this issue to me as part of GSSoC-EXT and Hacktoberfest.

**Comment by vedhcet-07** [comment]
> Hey! I would love to resolve this issue quickly so that others can run the project locally and contribute to various features. Please assign this issue to me as part of GSSoC-EXT and Hacktoberfest.

can you tell me how to test this on my local machine .  i am unable to try it

**Comment by Dnyaneshpise** [comment]
It was already resolved now
