### ISSUE TITLE
Display Log In/ Log Out Button on Home Page

### ISSUE THREAD

**Issue by abir499-ban** [jinx-vi-0/BlogLog#54]
This is a feature which will display a Log In Button on the home page when a user is not signed In and similarly when the user will be signed in, he/she will see a Log Out button on the Homepage.

For now, there is no Log In button on the Home page and hence we need to manually go the `/admin` route to get ourselves signed in. The Log In button  on the Homepage will direct a non signed In user to the sign in page, and hence will enhance the overall user experience. 
Also there is no show password feature on the password enter input. The feature to toggle between show password and hide password will allow the user to effortlessly sign in into the application.

@jinx-vi-0  please assign me this issue

**Comment by adarsh-site** [comment]
Assigned @abir499-ban

**Comment by abir499-ban** [comment]
@jinx-vi-0  Thank you sir for assigning it to me. Will start working on it ASAP.
