### ISSUE TITLE
Notifications for New Comments or Posts.

### ISSUE THREAD

**Issue by darshinihoney** [jinx-vi-0/BlogLog#56]
The Notifications for New Comments or Posts feature sends email alerts to users when they log in via email. Users are notified of new comments on their posts or when new content is published by others they follow. This ensures they stay updated and engaged with the platform, even when they are not actively browsing.

@jinx-vi-0 please assign me this issue

**Comment by adarsh-site** [comment]
Assigned @darshinihoney

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.

**Comment by darshinihoney** [comment]
> I would like to work on this, kindly assign me this issue.

I'm already working on it

**Comment by adarsh-site** [comment]
please solve the issue by tomorrow.

**Comment by darshinihoney** [comment]
@jinx-vi-0 Can I replace with other small issue i.e  toggle the visibility of the password in register page as I am not able to add the above feature.
