### ISSUE TITLE
Add Issue Templates to the Repository

### ISSUE THREAD

**Issue by aashika-j18** [jinx-vi-0/BlogLog#57]
Hello @jinx-vi-0 !

I would like to contribute to this repository by adding an issue template to help standardize the issue reporting process. This would make it easier for users to report bugs, request features, and provide relevant information.

I am currently participating in GSSoC-EXT and Hacktoberfest, so I would appreciate it if you could add the required labels.

Could you please assign this issue to me so I can start working on it?

**Comment by jinx-vi-0** [comment]
Assigned @aashika-j18
