### ISSUE TITLE
Authentication for Regular User's

### ISSUE THREAD

**Issue by 1510darshan** [jinx-vi-0/BlogLog#60]
There is no backend for login and signup for regular user.
If you sign these task to me I will create Backend for user authentiaction.
I can also implement email varification

**Comment by adarsh-site** [comment]
Assigned @1510darshan . Also add signup using google.

**Comment by 1510darshan** [comment]
yes sir sure

**Comment by rishabh7923** [comment]
Since there was no update regarding issue,
I would love to work on this.

**Comment by adarsh-site** [comment]
Assigned @rishabh7923

**Comment by rishabh7923** [comment]
I don't think it was level 2 work 😅
