### ISSUE TITLE
Create a CONTRIBUTING.md file for the project.

### ISSUE THREAD

**Issue by Suraj-kumar00** [jinx-vi-0/BlogLog#61]
1. Creating `CONTRIBUTING.md` file for the project is an open source standard.
2. This will include all the guidelines for the contributors to get start in a very structural and appropriate way.
- [x] I would like to work on this issue please assign it to me.

**Comment by adarsh-site** [comment]
We are no longer accepting any documentation-related issues. If you still want to proceed with this, you are good to go. However, please note that this issue will not receive any level.
