### ISSUE TITLE
Authorization Issue at Signup

### ISSUE THREAD

**Issue by rishabh7923** [jinx-vi-0/BlogLog#65]
As soon as I enter my details and click on 'Sign Up,' it redirects me to the dashboard, which says "Unauthorized". Below is the video showing issue.
Instead of this unexpected behavior, it should automatically log the user in and redirect them to the dashboard.

https://github.com/user-attachments/assets/9dc02f6a-4dcd-485b-810b-7d3e0882a0ee

**If allowed, I would like to work on this issue**

**Comment by adarsh-site** [comment]
Assigned @rishabh7923
