### ISSUE TITLE
Add Blog APIs

### ISSUE THREAD

**Issue by haseebzaki-07** [jinx-vi-0/BlogLog#67]
**Is your feature request related to a problem? Please describe.**
I want to add blogging APIs for the creation, updation, deletion and fetching of the blogs.

**Describe the solution you'd like**
I will create respective handlers/controllers for the purpose.

**Comment by MOHINI1403** [comment]
i guess they are already created but organised in a specified backend format

**Comment by haseebzaki-07** [comment]
@MOHINI1403 Hey I searched the codebase but didn't find any controllers/Api interesting this. Could you please let me know if i am wrong and if not then I will be pleased working on this issue.
