### ISSUE TITLE
Add Ai Chat bot

### ISSUE THREAD

**Issue by skanarul8002** [jinx-vi-0/BlogLog#69]
### **Is your feature request related to a problem? Please describe.**
Currently, the blog platform lacks an interactive feature for user engagement. I'm frustrated when users can't get instant support or answers to their questions while browsing or interacting with the platform. This reduces overall user experience and satisfaction.

### **Describe the solution you'd like**
I would like to implement an AI chatbot that assists users in real-time, providing answers to frequently asked questions, helping them navigate the blog, and offering suggestions based on their interests. The chatbot should be integrated as a floating widget on the site and accessible from any page.

### **Describe alternatives you've considered**
Alternatively, we could use a static FAQ page, but it lacks interactivity and doesn’t offer personalized suggestions. A live chat system could be considered, but it requires constant human monitoring, which is resource-intensive.

### **Additional context**
The AI chatbot could leverage popular NLP platforms such as Dialogflow or IBM Watson to provide more intelligent and context-aware responses. Integration with existing APIs can provide users with personalized content suggestions and help streamline their experience on the platform.

**Comment by dhawalbisht** [comment]
Can you assign it to me?
