### ISSUE TITLE
User profile page and blog association to a user

### ISSUE THREAD

**Issue by 0vai5** [jinx-vi-0/BlogLog#7]
I want to create a user profile page that displays all blogs authored by the respective user. Additionally, each blog should be directly associated with the user, allowing the system to correctly attribute blogs to the user in both the frontend (display) and backend (database). This will ensure that the user's profile shows their authored content clearly and is properly linked in the database.

Label: gssoc-ext

Please assign it to me @jinx-vi-0

**Comment by adarsh-site** [comment]
Assigned @0vai5

**Comment by adarsh-site** [comment]
completed #16
