### ISSUE TITLE
readme deployment instructions are not correct and user friendly 

### ISSUE THREAD

**Issue by Anandha-Vihari** [jinx-vi-0/BlogLog#71]
i will change readme file instruction,to  deploy ,so that beginners can understand

and also i will add code of conduct and contributor files 

please assign me this under ggsocext level2 or higher

@jinx-vi-0

**Comment by adarsh-site** [comment]
Thank you for bringing up this issue. However, we are no longer accepting changes to the documentation. I believe that the README already includes all the necessary information to start contributing.

**Comment by Anandha-Vihari** [comment]
@jinx-vi-0 once check .env setup in readme file,it is unclear.....

**Comment by adarsh-site** [comment]
Yes, I understand, but it will be updated in the next pull request. There is no need to create a pull request just for this.

**Comment by Anandha-Vihari** [comment]
@jinx-vi-0 what about some more documnetation changes ,adding sitemap and robots pages and deploy it in github pages??..

**Comment by Anandha-Vihari** [comment]
??
