### ISSUE TITLE
Duplicate Session Middleware in app.js causing Potential Conflicts

### ISSUE THREAD

**Issue by chikatlarakesh** [jinx-vi-0/BlogLog#72]
### **Describe the bug**
There are two instances of the `session()` middleware in `app.js`, which could potentially cause conflicts in session management. The first instance is redundant as the second instance already handles session storage with MongoDB integration.

### **To Reproduce**
1. Open the `app.js` file.
2. Review the two instances of `session()` middleware.
3. Observe that both are performing session handling, leading to a potential conflict.
4. See that the application may face issues in properly storing sessions.

### **Expected behavior**
Only one instance of the `session()` middleware should be used. The second instance, which integrates MongoDB session storage, should be sufficient for proper session handling.

### **Screenshots**
(Not applicable, as this is a code-related issue.)

### **Desktop (please complete the following information):**
 - OS: [e.g. Windows, macOS]
 - Browser: Not applicable (server-side issue)
 - Version: N/A

### **Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

### **Additional context**
The issue arises because the first session middleware is unnecessary and could interfere with MongoDB session handling, especially in a production environment where proper session management is critical.

**Comment by adarsh-site** [comment]
Assigned @chikatlarakesh
