### ISSUE TITLE
Adding semantic search using Gemini API

### ISSUE THREAD

**Issue by anishka25** [jinx-vi-0/BlogLog#74]
**Is your feature request related to a problem? Please describe.**
For now the semantic search of thoughts is not possible.
**Describe the solution you'd like**
Adding semantic search using Gemini API

**Comment by adarsh-site** [comment]
Could you please describe your issue in detail ?

**Comment by anishka25** [comment]
@jinx-vi-0 So basically gemini can handle something called embeddings. Using its api which is free 1500 requests/day, we can implement a functionality that helps user search his/her thoughts by using natural language/english which can be related to the thought but might/might not be exactly word to word search.
