### ISSUE TITLE
Development of Responsive "Contact Us" Page – Frontend Contribution

### ISSUE THREAD

**Issue by vedhcet-07** [jinx-vi-0/BlogLog#8]
I would like to contribute to the Personalized Blog project by developing the frontend for the "**Contact Us**" page. This page will allow visitors to easily get in touch with the blog owner or admin by submitting their queries or feedback through a clean and responsive form.

**Key Features:**

- User-friendly Form: Fields such as Name, Email, Subject, and Message, designed with clear labels and placeholders.
- Responsive Layout: The design will adjust seamlessly across desktop, tablet, and mobile devices using HTML and Tailwind CSS.
- Form Validation: Input validation to ensure all fields are correctly filled out before submission, improving the overall user experience.
- Aesthetic Design: Implementing Material-UI components to make the form visually appealing and in line with the blog's theme.

I would love to take on this task and request that it be assigned to me under **Hacktoberfest and GSSoC**. I'm excited to contribute and help enhance this blog project!

Thank you!

**Comment by adarsh-site** [comment]
Assigned @vedhcet-07

**Comment by vedhcet-07** [comment]
> Assigned @vedhcet-07

Thank you sir . I will work on this . Please share your personal number or email to me so that i can seek approval from you . my email vedhcet.personal@gmail.com

**Comment by adarsh-site** [comment]
you can find my discord and gmail on my github account. 

prefer discord for conversations.
