### ISSUE TITLE
Input Validation For SignUp/Register

### ISSUE THREAD

**Issue by rishabh7923** [jinx-vi-0/BlogLog#80]
Currently, you can input anything when signing in, and it will be accepted as a valid parameter, but this isn't ideal for the website. To address this, I plan to do the following:

- Implement input validation on the client side.
- Also, perform validation on the server side to ensure that if someone tries to bypass the client-side checks, we remain one step ahead.
- Show informational message for every incorrect input

**Comment by rishabh7923** [comment]
@jinx-vi-0 😶

**Comment by ScrumptiousLaroi** [comment]
assign me!

**Comment by adarsh-site** [comment]
Assigned @rishabh7923

**Comment by rishabh7923** [comment]
I don't think it was level 1 issue

**Comment by adarsh-site** [comment]
Sorry, I provided the wrong level. I’ll update it to reflect the correct level. Thanks for your understanding!
