### ISSUE TITLE
Feature: Blog Post Drafts

### ISSUE THREAD

**Issue by Anushka-Pote** [jinx-vi-0/BlogLog#82]
**Is your feature request related to a problem? Please describe.**
Description: Add a "Save as Draft" option so that users can save unfinished blog posts without publishing them immediately.

**Describe the solution you'd like**
Add a status field (published/draft) to the blog post schema.
Modify the post creation form to include a "Save as Draft" button.
Show draft posts only in the user’s personal view, while published posts are visible to everyone.

**Describe alternatives you've considered**
Many users might not be ready to publish their posts immediately. Drafts allow them to save their work and return later to finish and publish.

**Comment by adarsh-site** [comment]
Assigned @Anushka-Pote

**Comment by adarsh-site** [comment]
Don't just raise unnecessary pr.

**Comment by Anushka-Pote** [comment]
I did not raise unnecessary PR, I was assigned this issue and then tried to solve it, I made the changes and then only raised the Pr. Like the drafts for the blogs or posts to get saved in the localStorage for future use

**Comment by Anushka-Pote** [comment]
Any other expectations or any errors happening, do inform. or since this issue has already been closed, not informing also seems okay
