### ISSUE TITLE
Footer UI is breaking in /dashboard

### ISSUE THREAD

**Issue by Siddhi-sahu** [jinx-vi-0/BlogLog#83]
**Describe the bug**
the footer is not at the sticking at the very end which it should

**Expected behavior**
the footer should stick to the very end of the page regardless of if blogs are present or not

**Screenshots**
![image](https://github.com/user-attachments/assets/7307fbb7-0944-4457-b902-f69c7f891efe)

**Comment by adarsh-site** [comment]
Assigned @Siddhi-sahu

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.
