### ISSUE TITLE
Missing Confirmation for Post Deletion

### ISSUE THREAD

**Issue by divyalakshmi0** [jinx-vi-0/BlogLog#84]
## Description: 
When a user deletes a post, there is no confirmation dialog. Accidental deletions can occur, leading to loss of data.

## Proposed Solution:
- Implement a client-side confirmation popup (using JavaScript) before deleting a post.
- Ensure that the backend route in Express handles deletions properly, only after user confirmation.

**Comment by adarsh-site** [comment]
Assigned @divyalakshmi0
