### ISSUE TITLE
Add Post Likes or Reactions

### ISSUE THREAD

**Issue by divyalakshmi0** [jinx-vi-0/BlogLog#85]
## Description:
 Allow users to like or react to blog posts with different reactions (e.g., thumbs up, heart). This will increase user engagement on the platform and provide feedback to authors about their posts' popularity.

## Proposed Solution:

- Update the blog post schema to include a likes or reactions field (an array or a counter).
- Add a like or reaction button next to each post that allows users to react.
- Implement routes to handle user reactions (i.e., POST and DELETE routes to add/remove reactions).
- Show the total number of reactions next to each post on the blog feed.

## How It Will Be Useful:

- Increased User Engagement: Users will be more likely to interact with the platform, contributing to a more active user base.
- Content Feedback: Blog authors can receive real-time feedback on how their content is being received.
- Social Proof: Displaying reactions or likes on popular posts encourages new visitors to explore well-liked content, improving user retention.

**Comment by adarsh-site** [comment]
Assigned @divyalakshmi0
