### ISSUE TITLE
enhance BlogLog with a "Comments Feature"

### ISSUE THREAD

**Issue by sv410** [jinx-vi-0/BlogLog#87]
BlogLog: New Feature Idea
Feature: Tagging System for Blog Posts
Is your feature request related to a problem? Please describe. Currently, users can create and manage blog posts, but there’s no way to organize them with tags or categories. It can become difficult to navigate and find specific posts, especially when a user has many entries.

Describe the solution you'd like Implement a tagging system that allows users to add tags to their blog posts. Users should be able to:

Add multiple tags to a post.

Filter posts by tags.

Display a list of all tags available.

Describe alternatives you've considered

Using a search functionality to find posts, but it’s less efficient for categorization.

Manually organizing posts by title keywords, which is cumbersome.

Additional context This feature will greatly enhance the user experience by making it easier to categorize and search for specific blog posts. Here's how it might look in the interface:

Tag Input Field: Add a field to enter tags when creating or editing a post.

Tag Display: Show tags below each post title in the list view.

Filter by Tag: Add a sidebar or dropdown to filter posts by tags.

This new feature will make BlogLog even more user-friendly and powerful for managing blog content.

**Comment by adarsh-site** [comment]
Assigned @sv410

**Comment by rishabh7923** [comment]
Due to inactivity, 
I would like to work on the implementation of tags in blog

**Comment by adarsh-site** [comment]
Assigned @rishabh7923

**Comment by adarsh-site** [comment]
@rishabh7923 please solve the issue by tomorrow.

**Comment by rishabh7923** [comment]
Ohk
