### ISSUE TITLE
Add Tech Stack and Features to README for Better Contributor Guidance

### ISSUE THREAD

**Issue by RaginiSharma01** [jinx-vi-0/BlogLog#9]
Hi there! 👋

I noticed that the current README lacks some key details that could help new contributors get up to speed quickly. Specifically, it would be really helpful to:

List the technologies (tech stack) used in the project, so contributors know which languages, frameworks, or tools are involved.
Provide a brief section outlining the main features of the project. This would give contributors a clear understanding of what the project is about and what features are already implemented or need improvement.

I would love to contribute by updating the README to include:

A Tech Stack section, which lists the languages, frameworks, libraries, etc., used in the project.
A Features section that outlines the primary features of the project.
If needed, other sections that might provide helpful context to contributors (such as installation instructions, project structure, etc.).

**Comment by RaginiSharma01** [comment]
I would like to contribute to this issue. please assign me this task

**Comment by adarsh-site** [comment]
Documentation contributions are not encouraged; however, if you could make an exceptional contribution, then you are good to go.

Before submitting a pull request, please share your work in the Discord thread of this repository.

**Comment by adarsh-site** [comment]
refer issue #24 

submit a single pr with a complete documentation update.

**Comment by RaginiSharma01** [comment]
ok working on the documentation
