### ISSUE TITLE
improve the hero section 

### ISSUE THREAD

**Issue by shibasarkar** [jinx-vi-0/BlogLog#96]
There are two login buttons at the navbar & the navbar is not consistent on every page 
![Screenshot 2024-10-27 120540](https://github.com/user-attachments/assets/6b3e7ace-fed8-4cf7-9a49-a0b78c3502ba)
![Screenshot 2024-10-27 120523](https://github.com/user-attachments/assets/a1320143-a1de-489d-bf33-18973207c85c)

**Comment by shibasarkar** [comment]
@jinx-vi-0  could you please assign this to me

**Comment by adarsh-site** [comment]
Assigned @shibasarkar
